title: Dusty Burwell
#url: http://www.dustyburwell.com

# Github repositories
github_repo_url: https://github.com/dustyburwell/dustyburwell.github.com/

markdown: rdiscount
permalink: /:year/:month/:day/:title
future: false

lsi: true
paginate: 20

exclude:
- CNAME

plugins:
- jekyll-redirect-from
