title: Dusty Burwell
#url: http://www.dustyburwell.com

# Github repositories
github_repo_url: https://github.com/dustyburwell/dustyburwell.github.com/

permalink: /:year/:month/:day/:title
future: false

markdown: kramdown
lsi: true
paginate: 20
highlighter: rouge

exclude:
- CNAME

plugins:
- jekyll-redirect-from
- jekyll-paginate
